name: Verify External PR

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize, ready_for_review]
    branches:
      - dev

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: verify-version
        uses: actions-cool/verify-files-modify@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          forbid-files: "LICENSE"
          forbid-paths: ".github/"
          comment: |
            This file is protected from modification.
          close: true
