name: External PR Build

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Verify extension's schema
        run: grep "version" src/extension.yaml

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dtextcli
        uses: ./.github/actions/dtextcli-setup

      - name: Build extension using dtextcli
        uses: ./.github/actions/build
